using System.Collections.Generic;
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop
{
    using System;
    
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual List<Categories> Categories { get; set; }
        public virtual List<Orders> Orders { get; set; }
        public virtual List<OrdersProducts> OrdersProducts { get; set; }
        public virtual List<PickPoint> PickPoint { get; set; }
        public virtual List<Producers> Producers { get; set; }
        public virtual List<Products> Products { get; set; }
        public virtual List<ProductType> ProductType { get; set; }
        public virtual List<Status> Status { get; set; }
        public virtual List<Suppliers> Suppliers { get; set; }
        public virtual List<Users> Users { get; set; }
        public virtual List<UsersRole> UsersRole { get; set; }
    }
}
